function [entMat] = get_comm_motif_entropy(aMat,cMat,pMat,dMat,odMat)
% get the comm motif entropy for edge-wise probabilities
% eq. 10, https://doi.org/10.1038/s41467-017-02681-z
% 
% altered to include within-community probability

if nargin < 5
    entMat = -1 .* ( aMat.*log2(aMat) + ...
            cMat.*log2(cMat) + ...
            pMat.*log2(pMat) + ...
            dMat.*log2(dMat) ) ; 
else
    entMat = -1 .* ( aMat.*log2(aMat) + ...
        cMat.*log2(cMat) + ...
        pMat.*log2(pMat) + ...
        dMat.*log2(dMat) + ...
        odMat.*log2(odMat)) ; 
end

